dataset: 'replica'
meshing:
  # resolution: 0.1
  resolution: 0.08
  eval_rec: True
tracking:
  ignore_edge_W: 75
  ignore_edge_H: 75
  lr_T: 0.002
  lr_R: 0.001
  # pixels: 2000
  pixels: 4000
  # iters: 8
  iters: 16
mapping:
  # pixels: 4000
  pixels: 8000
  # iters: 15
  iters: 30
  vis_freq: 49
  every_frame: 5
  lr:
    fusion_lr: 3e-3
cam:
  # H: 680
  # W: 1200
  # fx: 600.0
  # fy: 600.0
  # cx: 599.5
  # cy: 339.5
  H: 480
  W: 640
  fx: 606.383605957031
  fy: 605.308898925781
  cx: 319.168640136719
  cy: 231.037185668945
  png_depth_scale: 1000.0
  crop_edge: 0
rendering:
  n_stratified: 32
  n_importance: 8
  learnable_beta: True